name        : youtube-dl
version     : 2016.05.10
release     : 44
source     :
    - http://yt-dl.org/downloads/latest/youtube-dl-2016.05.10.tar.gz : ccb96dd53b7bf7305db0430f8b3a2044fa24f5200903c95349e070f938ad0c3f
license     : GPL-2.0
component   : network.download
summary     : Small command-line program to download videos from youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
