name        : youtube-dl
version     : 2015.10.24
release     : 20
source     :
    - http://youtube-dl.org/downloads/2015.10.24/youtube-dl-2015.10.24.tar.gz : fa151e925b51f6b5ee154f25089d287832a9387e59561810fd5eac8d00ce3ae1
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
