name       : youtube-dl
version    : 2017.01.05
release    : 61
source     :
    - https://github.com/rg3/youtube-dl/releases/download/2017.01.05/youtube-dl-2017.01.05.tar.gz : 7670471d6000eebb17f5edf0c405bb3b2b99b20c6f500b6bbfb2d5678ecf3da6
license    : GPL-2.0
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
setup      : |
    sed -i 's|etc/bash_completion.d|share/bash-completion/completions|' setup.py
    sed -i 's|etc/fish/completions|share/fish/completions|' setup.py
install    : |
    python3 setup.py install --root=%installroot%
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
