name        : youtube-dl
version     : 2016.02.22
release     : 42
source     :
    - http://yt-dl.org/downloads/latest/youtube-dl-2016.02.22.tar.gz : 14cf17af94a23d451c1c8d2fcc8ee072ee99746d6bc7487c91043498599d630a
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
