name        : youtube-dl
version     : 2015.08.16
release     : 16
source     :
    - http://yt-dl.org/downloads/2015.08.16/youtube-dl-2015.08.16.tar.gz : 85ef29e55989bdde8ea1bf9084484288e2acf91bf9c9d2f6ee08380d427712e6
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - python3-devel
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
