name        : youtube-dl
version     : 2015.12.23
release     : 33
source     :
    - http://yt-dl.org/downloads/2015.12.23/youtube-dl-2015.12.23.tar.gz : fe7088979c78eb900c3db110a577866a01e1dd537cddda25258893f099fff9ba
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
