name       : youtube-dl
version    : 2019.03.18
release    : 117
source     :
    - https://github.com/ytdl-org/youtube-dl/releases/download/2019.03.18/youtube-dl-2019.03.18.tar.gz : 074688b416e97aff5ae9ce3764e313b9d6433bb34a16b206775fbc37e4c16164
license    : Unlicense
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-setuptools
setup      : |
    %patch -p1 < $pkgfiles/add-shell-completions.patch
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
    mv $installdir/usr/share/zsh/site-functions/youtube-dl.zsh $installdir/usr/share/zsh/site-functions/_youtube-dl
