name        : youtube-dl
version     : 2015.12.21
release     : 32
source     :
    - http://yt-dl.org/downloads/2015.12.21/youtube-dl-2015.12.21.tar.gz : 7a61ccbc3cd55e712b2fb94a7dedff5052548bbebab9f8c441feec8a02748d4d
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
