name       : youtube-dl
version    : 2018.05.18
release    : 93
source     :
    - https://github.com/rg3/youtube-dl/releases/download/2018.05.18/youtube-dl-2018.05.18.tar.gz : bc548ad8ab8fad0ddfd7c7ad54fd5025ef424a727b1e302a99881784cc862087
license    : Unlicense
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-setuptools
setup      : |
    sed -i 's|etc/bash_completion.d|share/bash-completion/completions|' setup.py
    sed -i 's|etc/fish/completions|share/fish/completions|' setup.py
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
