name       : yt-dlp
version    : 2021.12.01
release    : 180
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2021.12.01.tar.gz : c3ae873c1ab51399ae1024db65a28ee06681328ca87da69c0af03edaa04c6770
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-websockets
    - python3-pycryptodome
setup      : |
    #  pycryptodome is 100% equivalent, so stop ´pip3 check´ from complaining
    sed -i "s:pycryptodomex:pycryptodome:" setup.py
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
