name       : youtube-dl
version    : 2017.04.26
release    : 70
source     :
    - https://github.com/rg3/youtube-dl/releases/download/2017.04.26/youtube-dl-2017.04.26.tar.gz : c320c8301a63ad97c099359c8b205d14c130b4f816dd92f0f5e68481628cfc47
license    : GPL-2.0
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
setup      : |
    sed -i 's|etc/bash_completion.d|share/bash-completion/completions|' setup.py
    sed -i 's|etc/fish/completions|share/fish/completions|' setup.py
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
