name       : yt-dlp
version    : 2022.02.04
release    : 184
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.02.04.tar.gz : 32f80d72648719711c89f3a807425e6042640ff7a330ec1d60c58c4f49e42c5b
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-websockets
    - python3-pycryptodome
setup      : |
    #  pycryptodome is 100% equivalent, so stop ´pip3 check´ from complaining
    sed -i "s:pycryptodomex:pycryptodome:" setup.py
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
