name        : youtube-dl
version     : 2015.06.04
release     : 9
source     :
    - http://yt-dl.org/downloads/2015.06.04.1/youtube-dl-2015.06.04.1.tar.gz : cffb1edb9637962e6a2ea1d26284f52aa53c7f5cd2a3e1e94a21f414aa606566
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - python3-devel
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
