name        : youtube-dl
version     : 2015.11.24
release     : 27
source     :
    - http://yt-dl.org/downloads/2015.11.24/youtube-dl-2015.11.24.tar.gz : cceeb606e723c0291de85eecb9a551ca887f3be4db786ad621011a9201a482b1
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
