name       : youtube-dl
version    : 2016.07.09
release    : 48
source     :
    - https://github.com/rg3/youtube-dl/archive/2016.07.09.tar.gz : be38072a53a8c1662126821b1c0b76b702b15bd283543662f1f0549509e197c1
license    : GPL-2.0
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
