name       : youtube-dl
version    : 2021.06.06
release    : 177
source     :
    - https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl-2021.06.06.tar.gz : 3ccb0e4db9fd172338ed1c32bae0be2f716458dca4143e55732ff55260b20ac3
license    : Unlicense
component  : network.download
homepage   : http://ytdl-org.github.io/youtube-dl/
summary    : youtube-dl is a small command-line program for downloading videos from YouTube and other platforms
description: |
    youtube-dl is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - python3
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-shell-completions-to-correct-place.patch
    %make pypi-files zsh-completion
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
    mv $installdir/usr/share/zsh/site-functions/youtube-dl.zsh $installdir/usr/share/zsh/site-functions/_youtube-dl
    ln -s /usr/bin/youtube-dl $installdir/usr/bin/yt-dlc
