name        : youtube-dl
version     : 2015.08.09
release     : 15
source     :
    - http://yt-dl.org/downloads/2015.08.09/youtube-dl-2015.08.09.tar.gz : 01bd26ceb7bfde7bef2528666807241354087cf01b198b3d48623ee5e3c4b746
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - python3-devel
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
