name       : youtube-dl
version    : 2019.09.12.1
release    : 134
source     :
    - https://github.com/ytdl-org/youtube-dl/releases/download/2019.09.12.1/youtube-dl-2019.09.12.1.tar.gz : ce27a84e861e4d234768bf3a466d3e0f9af7c58f2aac84b940feb2ce6640fb40
license    : Unlicense
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/add-shell-completions.patch
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
    mv $installdir/usr/share/zsh/site-functions/youtube-dl.zsh $installdir/usr/share/zsh/site-functions/_youtube-dl
