name       : yt-dlc
version    : 2020.10.26
release    : 161
source     :
    - https://github.com/blackjack4494/yt-dlc/archive/2020.10.26.tar.gz : e0a777b90c55b8d8a64f0e1b7b2742d849484de00ef8055ffbc25fd7250148a2
license    : Unlicense
component  : network.download
homepage   : https://github.com/blackjack4494/yt-dlc/
summary    : yt-dlc is a fork of youtube-dl, a smmall command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlc is a fork of youtube-dl, a smmall command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
builddeps  :
    - pkgconfig(python3)
    - pandoc
setup      : |
    %patch -p1 < $pkgfiles/add-shell-completions.patch
    %make pypi-files zsh-completion
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dlc.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dlc
    mv $installdir/usr/share/zsh/site-functions/youtube-dlc.zsh $installdir/usr/share/zsh/site-functions/_youtube-dlc
