name        : youtube-dl
version     : 2015.12.06
release     : 29
source     :
    - http://yt-dl.org/downloads/2015.12.06/youtube-dl-2015.12.06.tar.gz : 130be9fe481ce17a8d716e58324c837179099c5bb0789194e8e51b79b7c7b279
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
