name       : yt-dlp
version    : 2022.03.08.1
release    : 186
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.03.08.1.tar.gz : db6061a501f15d230d2bfdfbb661528f50a61943bc35be7601db6048f56283ca
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-websockets
    - python3-pycryptodome
setup      : |
    #  pycryptodome is 100% equivalent, so stop ´pip3 check´ from complaining
    sed -i "s:pycryptodomex:pycryptodome:" setup.py
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
