name        : youtube-dl
version     : 2016.03.14
release     : 43
source     :
    - http://yt-dl.org/downloads/latest/youtube-dl-2016.03.14.tar.gz : 59ad34e573ecf190cf61ebfdf91878e12fc826d422e40d85237168b88d36d7a2
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
