name       : yt-dlp
version    : 2022.08.14
release    : 195
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.08.14.tar.gz : 6675444dd1740be5d5d95646ff5e24d95935b0030e1b8b24b198e12d1d0ec228
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-certifi
    - python-websockets
    - python3-pycryptodome
setup      : |
    %patch -p1 < $pkgfiles/exclude_devscripts_from_install.patch
    # Adjust requirement for pycryptodome and optional dependencies
    sed -ri requirements.txt -e "s/^(pycryptodome)x/\1/" -e "/^(brotli.*)/d"
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
