name       : yt-dlc
version    : 2020.11.11
release    : 165
source     :
    - https://github.com/blackjack4494/yt-dlc/archive/2020.11.11-3.tar.gz : 649f8ba9a6916ca45db0b81fbcec3485e79895cec0f29fd25ec33520ffffca84
license    : Unlicense
component  : network.download
homepage   : https://github.com/blackjack4494/yt-dlc/
summary    : yt-dlc is a fork of youtube-dl, a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlc is a fork of youtube-dl, a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - python3
setup      : |
    %patch -p1 < $pkgfiles/add-shell-completions.patch
    %make pypi-files zsh-completion
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/share/bash-completion/completions/youtube-dlc.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dlc
    mv $installdir/usr/share/zsh/site-functions/youtube-dlc.zsh $installdir/usr/share/zsh/site-functions/_youtube-dlc
