name        : youtube-dl
version     : 2015.11.10
release     : 22
source     :
    - http://yt-dl.org/downloads/2015.11.10/youtube-dl-2015.11.10.tar.gz : c5a34ecbcf27ff34e1aae7c17732095309012e33ea9d1d4def613ca73f47e6be
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
