name        : youtube-dl
version     : 2015.12.09
release     : 30
source     :
    - http://yt-dl.org/downloads/2015.12.09/youtube-dl-2015.12.09.tar.gz : 93530a17c527cbf4e2c9e90dd98f3f43ef5a46b5daae9307a1549119c1583f87
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
