name        : youtube-dl
version     : 2016.01.01
release     : 34
source     :
    - http://yt-dl.org/downloads/2016.01.01/youtube-dl-2016.01.01.tar.gz : 732f37c99d71b4239d72d61dd32214b5a5a618671fb0629c8f8deb28209a172c
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
install    : |
    python3 setup.py install --root=%installroot%
