name       : youtube-dl
version    : 2016.09.24
release    : 52
source     :
    - https://github.com/rg3/youtube-dl/archive/2016.09.24.tar.gz : b1817eb015f75634f6cf3ecbdca7c4751d75bc12a82152dc821ff9ef205ecae2
license    : GPL-2.0
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
