name        : youtube-dl
version     : 2015.11.21
release     : 25
source     :
    - http://yt-dl.org/downloads/2015.11.21/youtube-dl-2015.11.21.tar.gz : 26ef30392579289ff54c54c6747fd0036a5fdf7429c55106f9703b0f9f19e339
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
