name        : youtube-dl
version     : 2016.01.23
release     : 39
source     :
    - http://yt-dl.org/downloads/2016.01.23/youtube-dl-2016.01.23.tar.gz : 449f4330fac38ed9f2bb2a547f42c1cfd705bab6a8839ff279fc4bd91f233154
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
