name        : youtube-dl
version     : 2015.11.19
release     : 24
source     :
    - http://yt-dl.org/downloads/2015.11.19/youtube-dl-2015.11.19.tar.gz : 2ed713c995a5cd837205eefa35d5df49179fa90cf634a4f222a31f2bde94e668
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
