name       : yt-dlp
version    : 2022.11.11
release    : 199
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.11.11.tar.gz : eff1b2effb599268db46efe56563ffbfc8006090e05f904c8aacf6efddb410f6
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-certifi
    - python-websockets
    - python3-pycryptodome
setup      : |
    # Adjust requirement for pycryptodome and optional dependencies
    sed -ri requirements.txt -e "s/^(pycryptodome)x/\1/" -e "/^(brotli.*)/d"
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
