name       : youtube-dl
version    : 2016.11.27
release    : 57
source     :
    - https://github.com/rg3/youtube-dl/releases/download/2016.11.27/youtube-dl-2016.11.27.tar.gz : 6ecc3996e28b6274d159643641a964098549b4cb8b33a3a3481148b88166e2cc
license    : GPL-2.0
component  : network.download
summary    : Small command-line program to download videos from youtube
description: |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
setup      : |
    sed -i 's|etc/bash_completion.d|share/bash-completion/completions|' setup.py
    sed -i 's|etc/fish/completions|share/fish/completions|' setup.py
install    : |
    python3 setup.py install --root=%installroot%
    mv $installdir/usr/share/bash-completion/completions/youtube-dl.bash-completion $installdir/usr/share/bash-completion/completions/youtube-dl
