name        : youtube-dl
version     : 2015.11.01
release     : 21
source     :
    - http://yt-dl.org/downloads/2015.11.01/youtube-dl-2015.11.01.tar.gz : 58a981cd708f30567382b97d6db336b25ca2279b759aea3a79e4d39a68351f3a
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
