name        : youtube-dl
version     : 2015.09.09
release     : 17
source     :
    - http://yt-dl.org/downloads/2015.09.09/youtube-dl-2015.09.09.tar.gz : fa2419fc47d0108b800c52dbe292fe1edf40259163035b57efb3b981e517511b
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - python3-devel
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
