name        : youtube-dl
version     : 2016.01.14
release     : 36
source     :
    - http://yt-dl.org/downloads/2016.01.14/youtube-dl-2016.01.14.tar.gz : 8fb4829219c591d0b9a94ebc7bda933db33d4b04d9875a8d725affdbc28e5aad
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
install    : |
    python3 setup.py install --root=%installroot%
