name       : yt-dlp
version    : 2022.09.01
release    : 197
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.09.01.tar.gz : 5a479b31a838ecf62a69b7880d069013528d2944a5e4088b84ae4105bc07d6c1
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
rundeps    :
    - mutagen
    - python3
    - python-certifi
    - python-websockets
    - python3-pycryptodome
setup      : |
    # Adjust requirement for pycryptodome and optional dependencies
    sed -ri requirements.txt -e "s/^(pycryptodome)x/\1/" -e "/^(brotli.*)/d"
    %make pypi-files
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
