name        : youtube-dl
version     : 2015.07.04
release     : 13
source     :
    - http://yt-dl.org/downloads/2015.07.04/youtube-dl-2015.07.04.tar.gz : cad69f6343c8e2f285ff2ff1b1b2d1631d6f28ac773555082a0f9c214d69dca5
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - python3-devel
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
