name        : youtube-dl
version     : 2015.11.27.1
release     : 28
source     :
    - http://yt-dl.org/downloads/2015.11.27.1/youtube-dl-2015.11.27.1.tar.gz : 35a7b2947200209bef9e642d1203e9d4a4103e279222c3ca3b5ee3adf3c8c535
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
