name        : youtube-dl
version     : 2016.02.13
release     : 41
source     :
    - http://yt-dl.org/downloads/2016.02.13/youtube-dl-2016.02.13.tar.gz : 8bb5cb62aad23fd3b049d9ffac76af6d76af8c18d68da3a3b9f602adaca1d534
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.5)
install    : |
    python3 setup.py install --root=%installroot%
