name        : youtube-dl
version     : 2016.01.09
release     : 35
source     :
    - http://yt-dl.org/downloads/2016.01.09/youtube-dl-2016.01.09.tar.gz : 463cfed59a1e2c6609a8e3d3354e0494833f1b249fe1979984b06a51ac5c904d
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
install    : |
    python3 setup.py install --root=%installroot%
