name        : youtube-dl
version     : 2015.11.23
release     : 26
source     :
    - http://yt-dl.org/downloads/2015.11.23/youtube-dl-2015.11.23.tar.gz : ce4cf088318fc088925cf2b7602f56f9bae410fa41502e5aff4879296fc1ad54
license     : GPL-2.0
summary     : Small command-line program to download videos form youtube
description : |
    youtube-dl is a small command-line program to download videos from YouTube.com and a few more sites
builddeps  :
    - pkgconfig(python-3.4)
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot%
